"""Local LLM client for Socratix - thin wrapper over the Ollama REST API.

Everything runs locally; there is no paid API or remote inference call.
Ollama exposes an HTTP server on ``http://localhost:11434`` once
``ollama serve`` is running (or the Ollama desktop app is open). We use the
``/api/chat`` endpoint with ``stream=false`` so the wrapper returns a single
string, which keeps later phases (diagnostic loop, teaching agent) simple.

Local-LLM tradeoff notes (called out per the project spec):
    * The default model below, Llama 3.1 8B, is small enough to run on a
      typical laptop GPU/CPU but materially weaker than GPT-4-class models
      at: strict JSON formatting, multi-step reasoning, and producing
      consistent classification labels. Phase 3 (diagnostic agent) compensates
      with a stricter-prompt retry path that calls this same wrapper.
    * Analogies generated by an 8B model are sometimes shallow or off-topic;
      Phase 7 (teaching agent) limits retries to 2 and then escalates to
      "needs human review" rather than looping forever.
    * Set ``OLLAMA_MODEL`` (env var) to swap models without code changes -
      e.g. ``mistral:7b-instruct`` if 8B is too slow on your machine.
"""

from __future__ import annotations

import json
import os
from typing import Any

import requests

OLLAMA_BASE_URL: str = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
DEFAULT_MODEL: str = os.environ.get("OLLAMA_MODEL", "llama3.1:8b")
DEFAULT_TIMEOUT_SECONDS: float = 120.0
DEFAULT_TEMPERATURE: float = 0.4

_HEALTH_CHECK_TIMEOUT: float = 3.0


class OllamaError(RuntimeError):
    """Base class for all LLM-client errors raised by this module."""


class OllamaUnavailableError(OllamaError):
    """Raised when the Ollama server is unreachable on ``OLLAMA_BASE_URL``."""


class OllamaModelMissingError(OllamaError):
    """Raised when the requested model is not pulled locally."""


class OllamaResponseError(OllamaError):
    """Raised when Ollama returns a non-2xx status or an unparseable body."""


def is_ollama_running(base_url: str = OLLAMA_BASE_URL) -> bool:
    """Return True if the Ollama REST API responds on ``base_url``.

    Performs a lightweight ``GET /api/tags`` call. Any connection error,
    timeout, or non-2xx status returns False - we never raise from here so
    callers can branch cleanly on availability.

    Args:
        base_url: Base URL of the Ollama HTTP server.

    Returns:
        True if Ollama responds with HTTP 2xx, False otherwise.
    """
    try:
        resp = requests.get(f"{base_url}/api/tags", timeout=_HEALTH_CHECK_TIMEOUT)
    except requests.RequestException:
        return False
    return resp.ok


def list_local_models(base_url: str = OLLAMA_BASE_URL) -> list[str]:
    """Return the names of models currently pulled on the local Ollama server.

    Args:
        base_url: Base URL of the Ollama HTTP server.

    Returns:
        A list of model name strings (e.g. ``["llama3.1:8b", "mistral:7b"]``).

    Raises:
        OllamaUnavailableError: If Ollama cannot be reached.
        OllamaResponseError: If the response body cannot be parsed.
    """
    try:
        resp = requests.get(f"{base_url}/api/tags", timeout=_HEALTH_CHECK_TIMEOUT)
    except requests.RequestException as exc:
        raise OllamaUnavailableError(
            f"Cannot reach Ollama at {base_url}. Is `ollama serve` running?"
        ) from exc

    if not resp.ok:
        raise OllamaResponseError(
            f"Ollama returned HTTP {resp.status_code} from /api/tags: {resp.text[:200]}"
        )

    try:
        payload = resp.json()
    except ValueError as exc:
        raise OllamaResponseError("Ollama /api/tags returned invalid JSON") from exc

    return [m.get("name", "") for m in payload.get("models", []) if m.get("name")]


def ask_llm(
    system_prompt: str,
    user_message: str,
    *,
    model: str = DEFAULT_MODEL,
    temperature: float = DEFAULT_TEMPERATURE,
    json_mode: bool = False,
    history: list[dict[str, str]] | None = None,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
    base_url: str = OLLAMA_BASE_URL,
) -> str:
    """Send a single prompt to the local LLM and return the assistant's reply.

    This is the primary entry point used by every later phase. It always
    issues a non-streaming ``/api/chat`` request so the entire reply is
    returned as one string.

    Args:
        system_prompt: System-role message that sets the assistant's role
            and constraints. Keep these in :mod:`socratix.prompts` (added in
            Phase 3) rather than inline.
        user_message: The student's (or pipeline's) message for this turn.
        model: Ollama model tag. Defaults to ``llama3.1:8b``; can be
            overridden per call or globally via the ``OLLAMA_MODEL`` env var.
        temperature: Sampling temperature in ``[0.0, 2.0]``. Defaults to
            0.4 - low enough to keep classification stable, high enough to
            avoid robotic teaching prose.
        json_mode: If True, pass ``format="json"`` so Ollama constrains the
            model's output to valid JSON. Used by the Phase 3 diagnostic
            classifier (note: smaller models still occasionally emit
            malformed JSON even in this mode, hence the retry path there).
        history: Optional list of additional ``{"role", "content"}`` dicts
            inserted between the system prompt and the user message - used
            by Phase 3+ for multi-turn Socratic dialogue.
        timeout: Per-request timeout in seconds. Local 8B inference on CPU
            can take 30-60s for longer responses, so the default is generous.
        base_url: Override the Ollama URL (mainly for tests).

    Returns:
        The assistant's reply as a string. May be empty if the model
        returned no content; never None.

    Raises:
        OllamaUnavailableError: If Ollama cannot be reached.
        OllamaModelMissingError: If ``model`` is not pulled locally
            (404 from Ollama with a recognizable error message).
        OllamaResponseError: For any other non-2xx response or malformed body.
    """
    messages: list[dict[str, str]] = [{"role": "system", "content": system_prompt}]
    if history:
        messages.extend(history)
    messages.append({"role": "user", "content": user_message})

    payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {"temperature": float(temperature)},
    }
    if json_mode:
        payload["format"] = "json"

    try:
        resp = requests.post(
            f"{base_url}/api/chat",
            json=payload,
            timeout=timeout,
        )
    except requests.ConnectionError as exc:
        raise OllamaUnavailableError(
            f"Cannot reach Ollama at {base_url}. Is `ollama serve` running?"
        ) from exc
    except requests.Timeout as exc:
        raise OllamaResponseError(
            f"Ollama request timed out after {timeout:.0f}s (model={model}). "
            "Try a smaller model (e.g. mistral:7b) or raise the timeout."
        ) from exc
    except requests.RequestException as exc:
        raise OllamaResponseError(f"Ollama request failed: {exc}") from exc

    if resp.status_code == 404 or _is_model_not_found(resp):
        raise OllamaModelMissingError(
            f"Model {model!r} is not pulled locally. Run:\n"
            f"    ollama pull {model}"
        )

    if not resp.ok:
        raise OllamaResponseError(
            f"Ollama returned HTTP {resp.status_code}: {resp.text[:300]}"
        )

    try:
        data = resp.json()
    except ValueError as exc:
        raise OllamaResponseError("Ollama returned invalid JSON") from exc

    content = data.get("message", {}).get("content", "")
    return content if isinstance(content, str) else ""


def _is_model_not_found(resp: requests.Response) -> bool:
    """Heuristic: Ollama sometimes returns 500 with a 'model not found' body."""
    if resp.ok:
        return False
    try:
        body = resp.json()
    except ValueError:
        return False
    err = str(body.get("error", "")).lower()
    return "not found" in err and "model" in err


def ask_llm_json(
    system_prompt: str,
    user_message: str,
    *,
    model: str = DEFAULT_MODEL,
    temperature: float = 0.2,
    history: list[dict[str, str]] | None = None,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
) -> dict[str, Any]:
    """Convenience wrapper that requests JSON output and parses it for you.

    Phase 3 (diagnostic classification) is the main caller. Temperature
    defaults lower than :func:`ask_llm` because we want deterministic-ish
    structured output. The function does NOT retry on parse failure - that
    fallback lives in the diagnostic module so the retry prompt can be
    stricter and domain-aware.

    Args:
        system_prompt: System prompt instructing the model to reply in JSON.
        user_message: The user payload.
        model: Ollama model tag.
        temperature: Sampling temperature; kept low for structured output.
        history: Optional conversation history.
        timeout: Per-request timeout in seconds.

    Returns:
        Parsed JSON object as a Python dict.

    Raises:
        OllamaError: Any of the underlying connection/model errors.
        json.JSONDecodeError: If the model returned non-JSON despite
            ``format=json``. Callers should catch this and retry with a
            stricter prompt - see the Phase 3 diagnostic module.
    """
    raw = ask_llm(
        system_prompt,
        user_message,
        model=model,
        temperature=temperature,
        json_mode=True,
        history=history,
        timeout=timeout,
    )
    return json.loads(raw)
